name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1
          bundler-cache: true
      - name: Install Ruby packages
        run: bundle install
      - name: Install Ubuntu packages
        run: sudo apt-get update && sudo apt-get install numactl libaio-dev libmysqlclient-dev
      - name: Setup MySQL and ProxySQL (docker-compose)
        run: docker-compose up -d
      - name: Wait until DBs are alive
        run: ./scripts/ci/wait-for-db.sh
        timeout-minutes: 2
      - name: Create test DB
        run: mysql -uroot -ppassword -P33005 -e "CREATE DATABASE test;"
      - name: Run integration tests
        run: bundle exec rake integration
      - name: Run unit tests
        run: bundle exec rake unit
