name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1
      - name: Install Ruby packages
        run: bundle install
      - name: Install Ubuntu packages
        run: sudo apt-get install numactl libaio-dev
      - name: Setup MySQL
        run: ./dbdeployer/install.sh
      - name: Run integration tests
        run: bundle exec rake integration
      - name: Run unit tests
        run: bundle exec rake unit
